CREATE TABLE IF NOT EXISTS `org_organization` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_code` varchar(128) NOT NULL,
  `display_name` varchar(256) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_code` (`tenant_id`, `organization_code`, `deleted`),
  KEY `idx_org_status_period` (`tenant_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Industry-neutral organization subject';

CREATE TABLE IF NOT EXISTS `org_organization_classification` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `type_namespace` varchar(512) NOT NULL,
  `type_code` varchar(128) NOT NULL,
  `type_version` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_class_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_class_type` (`tenant_id`, `organization_id`, `type_namespace`, `type_code`, `type_version`, `deleted`),
  KEY `idx_org_class_status` (`tenant_id`, `organization_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Versioned organization classification assignment';

CREATE TABLE IF NOT EXISTS `org_organization_capability` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `type_namespace` varchar(512) NOT NULL,
  `type_code` varchar(128) NOT NULL,
  `type_version` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_cap_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_cap_type` (`tenant_id`, `organization_id`, `type_namespace`, `type_code`, `type_version`, `deleted`),
  KEY `idx_org_cap_status` (`tenant_id`, `organization_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Versioned organization capability assignment';

CREATE TABLE IF NOT EXISTS `org_organization_relation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_organization_id` bigint unsigned NOT NULL,
  `target_organization_id` bigint unsigned NOT NULL,
  `type_namespace` varchar(512) NOT NULL,
  `type_code` varchar(128) NOT NULL,
  `type_version` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_rel_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_rel_identity` (`tenant_id`, `source_organization_id`, `target_organization_id`, `type_namespace`, `type_code`, `type_version`, `valid_from`, `deleted`),
  KEY `idx_org_rel_source` (`tenant_id`, `source_organization_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  KEY `idx_org_rel_target` (`tenant_id`, `target_organization_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  CONSTRAINT `chk_org_rel_distinct` CHECK (`source_organization_id` <> `target_organization_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Directed organization relationship';

CREATE TABLE IF NOT EXISTS `org_unit` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `parent_unit_id` bigint unsigned DEFAULT NULL,
  `unit_code` varchar(128) NOT NULL,
  `display_name` varchar(256) NOT NULL,
  `tree_path` varchar(2048) NOT NULL,
  `sort_order` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_unit_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_unit_code` (`tenant_id`, `organization_id`, `unit_code`, `deleted`),
  KEY `idx_org_unit_parent` (`tenant_id`, `organization_id`, `parent_unit_id`, `sort_order`, `deleted`),
  KEY `idx_org_unit_status` (`tenant_id`, `organization_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Primary organization unit tree';

CREATE TABLE IF NOT EXISTS `org_unit_relation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_unit_id` bigint unsigned NOT NULL,
  `target_unit_id` bigint unsigned NOT NULL,
  `type_namespace` varchar(512) NOT NULL,
  `type_code` varchar(128) NOT NULL,
  `type_version` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_unit_rel_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_unit_rel_identity` (`tenant_id`, `source_unit_id`, `target_unit_id`, `type_namespace`, `type_code`, `type_version`, `valid_from`, `deleted`),
  KEY `idx_org_unit_rel_source` (`tenant_id`, `source_unit_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  KEY `idx_org_unit_rel_target` (`tenant_id`, `target_unit_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  CONSTRAINT `chk_org_unit_rel_distinct` CHECK (`source_unit_id` <> `target_unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Auxiliary organization unit relationship';

CREATE TABLE IF NOT EXISTS `org_person` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `person_code` varchar(128) NOT NULL,
  `display_name` varchar(256) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_person_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_person_code` (`tenant_id`, `person_code`, `deleted`),
  KEY `idx_org_person_status` (`tenant_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Tenant-scoped person subject';

CREATE TABLE IF NOT EXISTS `org_engagement` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `engagement_code` varchar(128) NOT NULL,
  `person_id` bigint unsigned NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `type_namespace` varchar(512) NOT NULL,
  `type_code` varchar(128) NOT NULL,
  `type_version` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_eng_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_eng_code` (`tenant_id`, `engagement_code`, `deleted`),
  KEY `idx_org_eng_person` (`tenant_id`, `person_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  KEY `idx_org_eng_subject` (`tenant_id`, `organization_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Person participation in an organization';

CREATE TABLE IF NOT EXISTS `org_position` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `org_unit_id` bigint unsigned DEFAULT NULL,
  `position_code` varchar(128) NOT NULL,
  `display_name` varchar(256) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_position_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_position_code` (`tenant_id`, `organization_id`, `position_code`, `deleted`),
  KEY `idx_org_position_unit` (`tenant_id`, `organization_id`, `org_unit_id`, `status`, `deleted`),
  KEY `idx_org_position_period` (`tenant_id`, `organization_id`, `status`, `valid_from`, `valid_to`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Position or responsibility slot';

CREATE TABLE IF NOT EXISTS `org_assignment` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `engagement_id` bigint unsigned NOT NULL,
  `organization_id` bigint unsigned NOT NULL,
  `org_unit_id` bigint unsigned NOT NULL,
  `position_id` bigint unsigned NOT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `valid_from` datetime(3) NOT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `active_primary_engagement_id` bigint unsigned GENERATED ALWAYS AS (
    CASE
      WHEN `is_primary` = 1 AND `status` = 'ACTIVE' AND `valid_to` IS NULL AND `deleted` = 0
      THEN `engagement_id`
      ELSE NULL
    END
  ) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_assignment_public_id` (`tenant_id`, `public_id`, `deleted`),
  UNIQUE KEY `uk_org_assignment_primary` (`tenant_id`, `active_primary_engagement_id`),
  KEY `idx_org_assignment_eng` (`tenant_id`, `engagement_id`, `status`, `valid_from`, `valid_to`, `deleted`),
  KEY `idx_org_assignment_unit` (`tenant_id`, `organization_id`, `org_unit_id`, `status`, `deleted`),
  KEY `idx_org_assignment_position` (`tenant_id`, `organization_id`, `position_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Versioned assignment of an engagement';
