CREATE TABLE IF NOT EXISTS `iam_user_group` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_code` varchar(64) NOT NULL,
  `group_name` varchar(128) NOT NULL,
  `group_type` varchar(32) NOT NULL DEFAULT 'STATIC',
  `owner_department_id` bigint unsigned NOT NULL DEFAULT 0,
  `description` varchar(500) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_user_group` (`tenant_id`, `group_code`, `deleted`),
  KEY `idx_iam_user_group_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM用户组';

CREATE TABLE IF NOT EXISTS `iam_user_group_member` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `member_type` varchar(32) NOT NULL DEFAULT 'DIRECT',
  `source_rule` varchar(64) DEFAULT NULL,
  `joined_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_user_group_member` (`tenant_id`, `group_id`, `user_id`, `deleted`),
  KEY `idx_iam_user_group_member_user` (`tenant_id`, `user_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM用户组成员';

CREATE TABLE IF NOT EXISTS `iam_password_policy` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `policy_code` varchar(64) NOT NULL,
  `policy_name` varchar(128) NOT NULL,
  `min_length` int NOT NULL DEFAULT 8,
  `max_length` int NOT NULL DEFAULT 20,
  `require_uppercase` tinyint(1) NOT NULL DEFAULT 1,
  `require_lowercase` tinyint(1) NOT NULL DEFAULT 1,
  `require_number` tinyint(1) NOT NULL DEFAULT 1,
  `require_special` tinyint(1) NOT NULL DEFAULT 0,
  `password_history_limit` int NOT NULL DEFAULT 5,
  `password_expire_days` int NOT NULL DEFAULT 0,
  `temp_password_expire_hours` int NOT NULL DEFAULT 24,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_password_policy` (`tenant_id`, `policy_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM密码策略';

CREATE TABLE IF NOT EXISTS `iam_login_policy` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `policy_code` varchar(64) NOT NULL,
  `policy_name` varchar(128) NOT NULL,
  `allow_password_login` tinyint(1) NOT NULL DEFAULT 1,
  `allow_sms_login` tinyint(1) NOT NULL DEFAULT 0,
  `allow_email_login` tinyint(1) NOT NULL DEFAULT 0,
  `allow_social_login` tinyint(1) NOT NULL DEFAULT 0,
  `force_mfa` tinyint(1) NOT NULL DEFAULT 0,
  `session_timeout_minutes` int NOT NULL DEFAULT 480,
  `max_failed_count` int NOT NULL DEFAULT 5,
  `lock_minutes` int NOT NULL DEFAULT 30,
  `ip_allowlist_json` json DEFAULT NULL,
  `device_trust_days` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_login_policy` (`tenant_id`, `policy_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM登录策略';

CREATE TABLE IF NOT EXISTS `iam_auth_policy` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `policy_code` varchar(64) NOT NULL,
  `policy_name` varchar(128) NOT NULL,
  `scope_type` varchar(32) NOT NULL,
  `scope_id` bigint unsigned NOT NULL DEFAULT 0,
  `resource_type` varchar(32) NOT NULL,
  `resource_code` varchar(128) NOT NULL,
  `effect_type` varchar(16) NOT NULL DEFAULT 'ALLOW',
  `condition_json` json DEFAULT NULL,
  `priority_no` int NOT NULL DEFAULT 100,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_auth_policy` (`tenant_id`, `policy_code`, `deleted`),
  KEY `idx_iam_auth_policy_scope` (`tenant_id`, `scope_type`, `scope_id`, `status`, `deleted`),
  KEY `idx_iam_auth_policy_resource` (`tenant_id`, `resource_type`, `resource_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM授权策略';

CREATE TABLE IF NOT EXISTS `int_datasource_health_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `datasource_id` bigint unsigned NOT NULL,
  `check_type` varchar(32) NOT NULL DEFAULT 'CONNECTIVITY',
  `health_status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `latency_ms` int NOT NULL DEFAULT 0,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `message_text` varchar(1000) DEFAULT NULL,
  `checked_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_int_datasource_health_log` (`tenant_id`, `datasource_id`, `checked_at`),
  KEY `idx_int_datasource_health_status` (`tenant_id`, `health_status`, `checked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据源健康检测日志';

CREATE TABLE IF NOT EXISTS `file_upload_session` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `bucket_id` bigint unsigned NOT NULL DEFAULT 0,
  `storage_id` bigint unsigned NOT NULL DEFAULT 0,
  `session_code` varchar(64) NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_size` bigint unsigned NOT NULL DEFAULT 0,
  `upload_mode` varchar(32) NOT NULL DEFAULT 'SINGLE',
  `part_count` int NOT NULL DEFAULT 1,
  `owner_user_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'INIT',
  `expire_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `extra_json` json DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_upload_session` (`tenant_id`, `session_code`, `deleted`),
  KEY `idx_file_upload_session_status` (`tenant_id`, `status`, `expire_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件上传会话';

CREATE TABLE IF NOT EXISTS `sched_job_alarm` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `job_id` bigint unsigned NOT NULL,
  `alarm_code` varchar(64) NOT NULL,
  `alarm_name` varchar(128) NOT NULL,
  `channel_type` varchar(32) NOT NULL DEFAULT 'WEBHOOK',
  `trigger_rule` varchar(64) NOT NULL DEFAULT 'ON_FAILURE',
  `receiver_json` json DEFAULT NULL,
  `template_code` varchar(64) DEFAULT NULL,
  `silence_minutes` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sched_job_alarm` (`tenant_id`, `job_id`, `alarm_code`, `deleted`),
  KEY `idx_sched_job_alarm_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务告警规则';

CREATE TABLE IF NOT EXISTS `gen_sql_artifact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL,
  `module_id` bigint unsigned NOT NULL DEFAULT 0,
  `table_id` bigint unsigned NOT NULL DEFAULT 0,
  `artifact_type` varchar(32) NOT NULL DEFAULT 'DDL',
  `dialect` varchar(32) NOT NULL DEFAULT 'MYSQL8',
  `file_name` varchar(255) DEFAULT NULL,
  `sql_text` longtext NOT NULL,
  `checksum_md5` varchar(32) DEFAULT NULL,
  `version_tag` varchar(64) DEFAULT NULL,
  `generated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_gen_sql_artifact_project` (`tenant_id`, `project_id`, `generated_at`),
  KEY `idx_gen_sql_artifact_table` (`tenant_id`, `table_id`, `generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='生成SQL产物';

CREATE TABLE IF NOT EXISTS `audit_security_incident` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `incident_code` varchar(64) NOT NULL,
  `incident_name` varchar(128) NOT NULL,
  `incident_type` varchar(32) NOT NULL,
  `severity_level` varchar(32) NOT NULL DEFAULT 'MEDIUM',
  `source_type` varchar(32) NOT NULL DEFAULT 'RULE',
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` varchar(64) DEFAULT NULL,
  `risk_rule_id` bigint unsigned NOT NULL DEFAULT 0,
  `trace_id` varchar(64) DEFAULT NULL,
  `detail_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `resolved_at` datetime(3) DEFAULT NULL,
  `resolved_by` bigint unsigned NOT NULL DEFAULT 0,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audit_security_incident` (`tenant_id`, `incident_code`),
  KEY `idx_audit_security_incident_status` (`tenant_id`, `status`, `occurred_at`),
  KEY `idx_audit_security_incident_rule` (`tenant_id`, `risk_rule_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='安全事件';
