CREATE TABLE IF NOT EXISTS `iam_session` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `tenant_code` varchar(64) NOT NULL,
  `session_no` varchar(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `username` varchar(64) NOT NULL,
  `nickname` varchar(128) DEFAULT NULL,
  `user_type` varchar(32) NOT NULL DEFAULT 'STAFF',
  `login_type` varchar(32) NOT NULL DEFAULT 'PASSWORD',
  `access_token_hash` varchar(64) NOT NULL,
  `login_ip` varchar(64) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `expire_at` datetime(3) NOT NULL,
  `last_access_at` datetime(3) DEFAULT NULL,
  `logout_at` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ONLINE',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_session_no` (`tenant_id`, `session_no`, `deleted`),
  UNIQUE KEY `uk_iam_session_token` (`access_token_hash`, `deleted`),
  KEY `idx_iam_session_user` (`tenant_id`, `user_id`, `status`, `deleted`),
  KEY `idx_iam_session_expire` (`tenant_id`, `expire_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM登录会话';

CREATE TABLE IF NOT EXISTS `iam_password_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_id` bigint unsigned NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `changed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `change_reason` varchar(64) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_iam_password_history_user` (`tenant_id`, `user_id`, `changed_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM密码历史';

CREATE TABLE IF NOT EXISTS `iam_login_fail_stat` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_id` bigint unsigned NOT NULL,
  `username` varchar(64) NOT NULL,
  `failed_count` int NOT NULL DEFAULT 0,
  `first_failed_at` datetime(3) DEFAULT NULL,
  `last_failed_at` datetime(3) DEFAULT NULL,
  `locked_until` datetime(3) DEFAULT NULL,
  `last_login_ip` varchar(64) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iam_login_fail_stat` (`tenant_id`, `user_id`, `deleted`),
  KEY `idx_iam_login_fail_locked` (`tenant_id`, `locked_until`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IAM登录失败统计';
