SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `saas_basics`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE `saas_basics`;

CREATE TABLE IF NOT EXISTS `plat_tenant_package` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `package_code` varchar(64) NOT NULL,
  `package_name` varchar(128) NOT NULL,
  `package_type` varchar(32) NOT NULL DEFAULT 'STANDARD',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `max_user_count` int unsigned NOT NULL DEFAULT 0,
  `max_dept_count` int unsigned NOT NULL DEFAULT 0,
  `max_storage_mb` int unsigned NOT NULL DEFAULT 0,
  `max_api_per_minute` int unsigned NOT NULL DEFAULT 0,
  `feature_flags_json` json DEFAULT NULL,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_code` (`package_code`),
  KEY `idx_package_status` (`status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户套餐';

CREATE TABLE IF NOT EXISTS `plat_tenant` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(64) NOT NULL,
  `tenant_name` varchar(128) NOT NULL,
  `tenant_type` varchar(32) NOT NULL DEFAULT 'ENTERPRISE',
  `package_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'TRIAL',
  `isolation_mode` varchar(32) NOT NULL DEFAULT 'SHARED_SCHEMA',
  `industry_code` varchar(64) DEFAULT NULL,
  `contact_name` varchar(64) DEFAULT NULL,
  `contact_mobile` varchar(32) DEFAULT NULL,
  `contact_email` varchar(128) DEFAULT NULL,
  `expire_at` datetime(3) DEFAULT NULL,
  `logo_file_id` bigint unsigned NOT NULL DEFAULT 0,
  `timezone` varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
  `locale` varchar(32) NOT NULL DEFAULT 'zh-CN',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`),
  KEY `idx_tenant_package` (`package_id`, `deleted`),
  KEY `idx_tenant_status` (`status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户';

CREATE TABLE IF NOT EXISTS `plat_tenant_quota` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `quota_code` varchar(64) NOT NULL,
  `quota_name` varchar(128) NOT NULL,
  `quota_value` bigint NOT NULL DEFAULT 0,
  `used_value` bigint NOT NULL DEFAULT 0,
  `alarm_threshold` bigint NOT NULL DEFAULT 0,
  `reset_cycle` varchar(32) NOT NULL DEFAULT 'MONTHLY',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quota_tenant_code` (`tenant_id`, `quota_code`, `deleted`),
  KEY `idx_quota_tenant` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户配额';

CREATE TABLE IF NOT EXISTS `plat_tenant_app` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `app_code` varchar(64) NOT NULL,
  `app_name` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `opened_at` datetime(3) DEFAULT NULL,
  `expired_at` datetime(3) DEFAULT NULL,
  `config_json` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_app` (`tenant_id`, `app_code`, `deleted`),
  KEY `idx_tenant_app_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户应用开通';

CREATE TABLE IF NOT EXISTS `plat_tenant_setting` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `setting_group` varchar(64) NOT NULL,
  `setting_key` varchar(128) NOT NULL,
  `setting_value` text,
  `value_type` varchar(32) NOT NULL DEFAULT 'STRING',
  `encrypted` tinyint(1) NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_setting` (`tenant_id`, `setting_group`, `setting_key`, `deleted`),
  KEY `idx_tenant_setting_group` (`tenant_id`, `setting_group`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户设置';

CREATE TABLE IF NOT EXISTS `plat_feature_flag` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `flag_key` varchar(128) NOT NULL,
  `flag_name` varchar(128) NOT NULL,
  `flag_scope` varchar(32) NOT NULL DEFAULT 'PLATFORM',
  `enabled` tinyint(1) NOT NULL DEFAULT 0,
  `rollout_rule_json` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_feature_flag` (`tenant_id`, `flag_key`, `deleted`),
  KEY `idx_feature_scope` (`flag_scope`, `enabled`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='功能开关';

CREATE TABLE IF NOT EXISTS `iam_department` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `dept_code` varchar(64) NOT NULL,
  `dept_name` varchar(128) NOT NULL,
  `dept_full_name` varchar(256) DEFAULT NULL,
  `tree_path` varchar(1024) DEFAULT NULL,
  `leader_user_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dept_code` (`tenant_id`, `dept_code`, `deleted`),
  KEY `idx_dept_parent` (`tenant_id`, `parent_id`, `deleted`),
  KEY `idx_dept_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='部门';

CREATE TABLE IF NOT EXISTS `iam_position` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `position_code` varchar(64) NOT NULL,
  `position_name` varchar(128) NOT NULL,
  `position_level` varchar(32) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_position_code` (`tenant_id`, `position_code`, `deleted`),
  KEY `idx_position_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='岗位';

CREATE TABLE IF NOT EXISTS `iam_employee` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `employee_no` varchar(64) NOT NULL,
  `employee_name` varchar(128) NOT NULL,
  `dept_id` bigint unsigned NOT NULL DEFAULT 0,
  `position_id` bigint unsigned NOT NULL DEFAULT 0,
  `mobile` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `gender` varchar(16) DEFAULT NULL,
  `hire_date` date DEFAULT NULL,
  `employee_status` varchar(32) NOT NULL DEFAULT 'ACTIVE',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employee_no` (`tenant_id`, `employee_no`, `deleted`),
  KEY `idx_employee_dept` (`tenant_id`, `dept_id`, `deleted`),
  KEY `idx_employee_position` (`tenant_id`, `position_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='员工';

CREATE TABLE IF NOT EXISTS `iam_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `user_code` varchar(64) NOT NULL,
  `username` varchar(64) NOT NULL,
  `nickname` varchar(128) DEFAULT NULL,
  `employee_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_type` varchar(32) NOT NULL DEFAULT 'STAFF',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `avatar_file_id` bigint unsigned NOT NULL DEFAULT 0,
  `mobile` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `last_login_at` datetime(3) DEFAULT NULL,
  `last_login_ip` varchar(64) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `password_changed_at` datetime(3) DEFAULT NULL,
  `need_reset_password` tinyint(1) NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_code` (`tenant_id`, `user_code`, `deleted`),
  UNIQUE KEY `uk_username` (`tenant_id`, `username`, `deleted`),
  KEY `idx_user_employee` (`tenant_id`, `employee_id`, `deleted`),
  KEY `idx_user_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户账号';

CREATE TABLE IF NOT EXISTS `iam_user_identity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `identity_type` varchar(32) NOT NULL,
  `identifier` varchar(128) NOT NULL,
  `credential` varchar(255) DEFAULT NULL,
  `verified` tinyint(1) NOT NULL DEFAULT 0,
  `bound_at` datetime(3) DEFAULT NULL,
  `last_used_at` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_identity` (`tenant_id`, `identity_type`, `identifier`, `deleted`),
  KEY `idx_identity_user` (`tenant_id`, `user_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户身份凭证';

CREATE TABLE IF NOT EXISTS `iam_role_group` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `group_code` varchar(64) NOT NULL,
  `group_name` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_group_code` (`tenant_id`, `group_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色组';

CREATE TABLE IF NOT EXISTS `iam_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `role_group_id` bigint unsigned NOT NULL DEFAULT 0,
  `role_code` varchar(64) NOT NULL,
  `role_name` varchar(128) NOT NULL,
  `role_type` varchar(32) NOT NULL DEFAULT 'BUSINESS',
  `data_scope_type` varchar(32) NOT NULL DEFAULT 'SELF',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_code` (`tenant_id`, `role_code`, `deleted`),
  KEY `idx_role_group` (`tenant_id`, `role_group_id`, `deleted`),
  KEY `idx_role_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色';

CREATE TABLE IF NOT EXISTS `iam_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `menu_type` varchar(32) NOT NULL DEFAULT 'MENU',
  `menu_code` varchar(64) NOT NULL,
  `menu_name` varchar(128) NOT NULL,
  `route_path` varchar(255) DEFAULT NULL,
  `component_path` varchar(255) DEFAULT NULL,
  `permission_code` varchar(128) DEFAULT NULL,
  `icon` varchar(64) DEFAULT NULL,
  `visible` tinyint(1) NOT NULL DEFAULT 1,
  `keep_alive` tinyint(1) NOT NULL DEFAULT 0,
  `sort_no` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `meta_json` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_menu_code` (`tenant_id`, `menu_code`, `deleted`),
  KEY `idx_menu_parent` (`tenant_id`, `parent_id`, `deleted`),
  KEY `idx_menu_type` (`tenant_id`, `menu_type`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单与操作点';

CREATE TABLE IF NOT EXISTS `iam_api_resource` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `resource_code` varchar(128) NOT NULL,
  `resource_name` varchar(128) NOT NULL,
  `http_method` varchar(16) NOT NULL,
  `url_pattern` varchar(255) NOT NULL,
  `auth_required` tinyint(1) NOT NULL DEFAULT 1,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_resource` (`tenant_id`, `resource_code`, `deleted`),
  KEY `idx_api_url` (`tenant_id`, `http_method`, `url_pattern`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='API 资源';

CREATE TABLE IF NOT EXISTS `iam_data_scope` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `scope_code` varchar(64) NOT NULL,
  `scope_name` varchar(128) NOT NULL,
  `scope_type` varchar(32) NOT NULL DEFAULT 'DEPT_AND_CHILDREN',
  `scope_rule_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_data_scope` (`tenant_id`, `scope_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据权限策略';

CREATE TABLE IF NOT EXISTS `iam_user_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `source_type` varchar(32) NOT NULL DEFAULT 'MANUAL',
  `expire_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`tenant_id`, `user_id`, `role_id`, `deleted`),
  KEY `idx_user_role_role` (`tenant_id`, `role_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色关联';

CREATE TABLE IF NOT EXISTS `iam_role_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `menu_id` bigint unsigned NOT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_menu` (`tenant_id`, `role_id`, `menu_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色菜单关联';

CREATE TABLE IF NOT EXISTS `iam_role_api` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `api_resource_id` bigint unsigned NOT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_api` (`tenant_id`, `role_id`, `api_resource_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色 API 权限关联';

CREATE TABLE IF NOT EXISTS `sys_dict_type` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `dict_code` varchar(64) NOT NULL,
  `dict_name` varchar(128) NOT NULL,
  `dict_scope` varchar(32) NOT NULL DEFAULT 'TENANT',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `cacheable` tinyint(1) NOT NULL DEFAULT 1,
  `ext_json` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type` (`tenant_id`, `dict_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型';

CREATE TABLE IF NOT EXISTS `sys_dict_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `dict_type_id` bigint unsigned NOT NULL,
  `item_value` varchar(64) NOT NULL,
  `item_label` varchar(128) NOT NULL,
  `item_color` varchar(32) DEFAULT NULL,
  `item_tag` varchar(32) DEFAULT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `sort_no` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `ext_json` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_item` (`tenant_id`, `dict_type_id`, `item_value`, `deleted`),
  KEY `idx_dict_item_parent` (`tenant_id`, `dict_type_id`, `parent_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典项';

CREATE TABLE IF NOT EXISTS `sys_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `config_group` varchar(64) NOT NULL,
  `config_key` varchar(128) NOT NULL,
  `config_name` varchar(128) NOT NULL,
  `config_value` text,
  `value_type` varchar(32) NOT NULL DEFAULT 'STRING',
  `encrypted` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_config` (`tenant_id`, `config_group`, `config_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统配置';

CREATE TABLE IF NOT EXISTS `sys_i18n_message` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `locale` varchar(32) NOT NULL,
  `message_group` varchar(64) NOT NULL,
  `message_key` varchar(128) NOT NULL,
  `message_value` text NOT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_i18n_message` (`tenant_id`, `locale`, `message_group`, `message_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='国际化文案';

CREATE TABLE IF NOT EXISTS `sys_sequence_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `rule_code` varchar(64) NOT NULL,
  `rule_name` varchar(128) NOT NULL,
  `prefix` varchar(32) DEFAULT NULL,
  `date_pattern` varchar(32) DEFAULT NULL,
  `seq_length` int NOT NULL DEFAULT 6,
  `step` int NOT NULL DEFAULT 1,
  `current_value` bigint NOT NULL DEFAULT 0,
  `reset_cycle` varchar(32) NOT NULL DEFAULT 'DAILY',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sequence_rule` (`tenant_id`, `rule_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务编码规则';

CREATE TABLE IF NOT EXISTS `int_datasource` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `datasource_code` varchar(64) NOT NULL,
  `datasource_name` varchar(128) NOT NULL,
  `datasource_type` varchar(32) NOT NULL DEFAULT 'MYSQL',
  `usage_type` varchar(32) NOT NULL DEFAULT 'BUSINESS',
  `host` varchar(255) DEFAULT NULL,
  `port` int DEFAULT NULL,
  `database_name` varchar(128) DEFAULT NULL,
  `username` varchar(128) DEFAULT NULL,
  `password_cipher` varchar(512) DEFAULT NULL,
  `jdbc_params` varchar(500) DEFAULT NULL,
  `config_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `test_status` varchar(32) NOT NULL DEFAULT 'UNTESTED',
  `last_tested_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_datasource_code` (`tenant_id`, `datasource_code`, `deleted`),
  KEY `idx_datasource_type` (`tenant_id`, `datasource_type`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据源';

CREATE TABLE IF NOT EXISTS `int_datasource_prop` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `datasource_id` bigint unsigned NOT NULL,
  `prop_key` varchar(128) NOT NULL,
  `prop_value` text,
  `encrypted` tinyint(1) NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_datasource_prop` (`tenant_id`, `datasource_id`, `prop_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据源扩展属性';

CREATE TABLE IF NOT EXISTS `int_api_client` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `client_code` varchar(64) NOT NULL,
  `client_name` varchar(128) NOT NULL,
  `client_type` varchar(32) NOT NULL DEFAULT 'INTERNAL',
  `access_key` varchar(128) NOT NULL,
  `secret_cipher` varchar(512) NOT NULL,
  `allowed_ips` varchar(1000) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `expired_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_client_code` (`tenant_id`, `client_code`, `deleted`),
  UNIQUE KEY `uk_api_access_key` (`access_key`),
  KEY `idx_api_client_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='开放 API 客户端';

CREATE TABLE IF NOT EXISTS `int_webhook_endpoint` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `endpoint_code` varchar(64) NOT NULL,
  `endpoint_name` varchar(128) NOT NULL,
  `target_url` varchar(500) NOT NULL,
  `sign_type` varchar(32) NOT NULL DEFAULT 'HMAC_SHA256',
  `secret_cipher` varchar(512) DEFAULT NULL,
  `timeout_ms` int NOT NULL DEFAULT 5000,
  `retry_times` int NOT NULL DEFAULT 3,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_webhook_code` (`tenant_id`, `endpoint_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Webhook 端点';

CREATE TABLE IF NOT EXISTS `int_integration_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `integration_type` varchar(32) NOT NULL,
  `integration_code` varchar(64) NOT NULL,
  `request_payload` json DEFAULT NULL,
  `response_payload` json DEFAULT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `trace_id` varchar(64) DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_integration_query` (`tenant_id`, `integration_type`, `integration_code`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='集成日志';

CREATE TABLE IF NOT EXISTS `file_storage` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `storage_code` varchar(64) NOT NULL,
  `storage_name` varchar(128) NOT NULL,
  `storage_type` varchar(32) NOT NULL DEFAULT 'MINIO',
  `endpoint` varchar(255) DEFAULT NULL,
  `bucket_default` varchar(128) DEFAULT NULL,
  `region_name` varchar(64) DEFAULT NULL,
  `access_key` varchar(128) DEFAULT NULL,
  `secret_cipher` varchar(512) DEFAULT NULL,
  `base_path` varchar(255) DEFAULT NULL,
  `public_base_url` varchar(500) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_storage_code` (`tenant_id`, `storage_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件存储器';

CREATE TABLE IF NOT EXISTS `file_bucket` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `storage_id` bigint unsigned NOT NULL,
  `bucket_code` varchar(64) NOT NULL,
  `bucket_name` varchar(128) NOT NULL,
  `bucket_type` varchar(32) NOT NULL DEFAULT 'PRIVATE',
  `bucket_path` varchar(255) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bucket_code` (`tenant_id`, `bucket_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件桶';

CREATE TABLE IF NOT EXISTS `file_object` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `bucket_id` bigint unsigned NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_ext` varchar(32) DEFAULT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `file_size` bigint unsigned NOT NULL DEFAULT 0,
  `md5_hex` varchar(32) DEFAULT NULL,
  `sha256_hex` varchar(64) DEFAULT NULL,
  `storage_path` varchar(500) NOT NULL,
  `visibility` varchar(32) NOT NULL DEFAULT 'PRIVATE',
  `biz_type` varchar(64) DEFAULT NULL,
  `version_no` int unsigned NOT NULL DEFAULT 1,
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_object` (`tenant_id`, `bucket_id`, `object_key`, `version_no`, `deleted`),
  KEY `idx_file_hash` (`tenant_id`, `md5_hex`, `deleted`),
  KEY `idx_file_biz_type` (`tenant_id`, `biz_type`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件对象';

CREATE TABLE IF NOT EXISTS `file_relation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `file_id` bigint unsigned NOT NULL,
  `biz_type` varchar(64) NOT NULL,
  `biz_id` varchar(64) NOT NULL,
  `field_name` varchar(64) DEFAULT NULL,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_file_relation_biz` (`tenant_id`, `biz_type`, `biz_id`, `deleted`),
  KEY `idx_file_relation_file` (`tenant_id`, `file_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件业务引用';

CREATE TABLE IF NOT EXISTS `file_access_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `file_id` bigint unsigned NOT NULL,
  `access_type` varchar(32) NOT NULL,
  `operator_user_id` bigint unsigned NOT NULL DEFAULT 0,
  `operator_ip` varchar(64) DEFAULT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 1,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_file_access_log` (`tenant_id`, `file_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件访问日志';

CREATE TABLE IF NOT EXISTS `sched_executor` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `executor_code` varchar(64) NOT NULL,
  `executor_name` varchar(128) NOT NULL,
  `executor_type` varchar(32) NOT NULL DEFAULT 'LOCAL',
  `address` varchar(255) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `heartbeat_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_executor_code` (`tenant_id`, `executor_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务执行器';

CREATE TABLE IF NOT EXISTS `sched_job` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `job_code` varchar(64) NOT NULL,
  `job_name` varchar(128) NOT NULL,
  `job_type` varchar(32) NOT NULL DEFAULT 'JAVA',
  `executor_id` bigint unsigned NOT NULL DEFAULT 0,
  `handler_name` varchar(128) NOT NULL,
  `job_param` text,
  `concurrency_policy` varchar(32) NOT NULL DEFAULT 'SERIAL',
  `misfire_policy` varchar(32) NOT NULL DEFAULT 'LAST',
  `retry_times` int NOT NULL DEFAULT 0,
  `timeout_seconds` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'DISABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_code` (`tenant_id`, `job_code`, `deleted`),
  KEY `idx_job_executor` (`tenant_id`, `executor_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='调度任务';

CREATE TABLE IF NOT EXISTS `sched_job_trigger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `job_id` bigint unsigned NOT NULL,
  `trigger_type` varchar(32) NOT NULL DEFAULT 'CRON',
  `cron_expr` varchar(128) DEFAULT NULL,
  `fixed_interval_seconds` int DEFAULT NULL,
  `next_fire_at` datetime(3) DEFAULT NULL,
  `last_fire_at` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_job_trigger` (`tenant_id`, `job_id`, `status`, `deleted`),
  KEY `idx_trigger_fire` (`tenant_id`, `next_fire_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务触发器';

CREATE TABLE IF NOT EXISTS `sched_job_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `job_id` bigint unsigned NOT NULL,
  `trigger_id` bigint unsigned NOT NULL DEFAULT 0,
  `execution_no` varchar(64) NOT NULL,
  `executor_id` bigint unsigned NOT NULL DEFAULT 0,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `run_status` varchar(32) NOT NULL DEFAULT 'RUNNING',
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `retry_count` int NOT NULL DEFAULT 0,
  `error_message` varchar(2000) DEFAULT NULL,
  `trace_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sched_execution_no` (`tenant_id`, `execution_no`),
  KEY `idx_sched_job_log` (`tenant_id`, `job_id`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务执行日志';

CREATE TABLE IF NOT EXISTS `gen_project` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_code` varchar(64) NOT NULL,
  `project_name` varchar(128) NOT NULL,
  `base_package` varchar(255) NOT NULL,
  `module_prefix` varchar(64) NOT NULL,
  `front_app_name` varchar(64) DEFAULT NULL,
  `author_name` varchar(64) DEFAULT NULL,
  `output_mode` varchar(32) NOT NULL DEFAULT 'ZIP',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_project` (`tenant_id`, `project_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成项目';

CREATE TABLE IF NOT EXISTS `gen_module` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL,
  `module_code` varchar(64) NOT NULL,
  `module_name` varchar(128) NOT NULL,
  `biz_domain` varchar(64) NOT NULL,
  `table_prefix` varchar(32) DEFAULT NULL,
  `permission_prefix` varchar(64) DEFAULT NULL,
  `route_prefix` varchar(128) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_module` (`tenant_id`, `project_id`, `module_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成模块';

CREATE TABLE IF NOT EXISTS `gen_table` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL,
  `module_id` bigint unsigned NOT NULL,
  `table_name` varchar(128) NOT NULL,
  `table_comment` varchar(255) NOT NULL,
  `entity_name` varchar(128) NOT NULL,
  `aggregate_name` varchar(128) DEFAULT NULL,
  `gen_style` varchar(32) NOT NULL DEFAULT 'CRUD',
  `tenant_column` varchar(64) NOT NULL DEFAULT 'tenant_id',
  `logic_delete_column` varchar(64) NOT NULL DEFAULT 'deleted',
  `version_column` varchar(64) NOT NULL DEFAULT 'version',
  `pk_strategy` varchar(32) NOT NULL DEFAULT 'ASSIGN_ID',
  `with_audit_columns` tinyint(1) NOT NULL DEFAULT 1,
  `with_detail_page` tinyint(1) NOT NULL DEFAULT 1,
  `with_export` tinyint(1) NOT NULL DEFAULT 1,
  `with_import` tinyint(1) NOT NULL DEFAULT 0,
  `with_tree` tinyint(1) NOT NULL DEFAULT 0,
  `template_group` varchar(64) NOT NULL DEFAULT 'DEFAULT',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_table` (`tenant_id`, `module_id`, `table_name`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成表定义';

CREATE TABLE IF NOT EXISTS `gen_column` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `table_id` bigint unsigned NOT NULL,
  `column_name` varchar(128) NOT NULL,
  `column_comment` varchar(255) NOT NULL,
  `db_type` varchar(64) NOT NULL,
  `java_type` varchar(128) NOT NULL,
  `ts_type` varchar(64) NOT NULL,
  `jdbc_type` varchar(64) DEFAULT NULL,
  `column_length` int DEFAULT NULL,
  `column_scale` int DEFAULT NULL,
  `nullable` tinyint(1) NOT NULL DEFAULT 1,
  `pk_flag` tinyint(1) NOT NULL DEFAULT 0,
  `insertable` tinyint(1) NOT NULL DEFAULT 1,
  `updatable` tinyint(1) NOT NULL DEFAULT 1,
  `list_flag` tinyint(1) NOT NULL DEFAULT 1,
  `detail_flag` tinyint(1) NOT NULL DEFAULT 1,
  `form_flag` tinyint(1) NOT NULL DEFAULT 1,
  `query_flag` tinyint(1) NOT NULL DEFAULT 0,
  `query_type` varchar(32) DEFAULT NULL,
  `dict_code` varchar(64) DEFAULT NULL,
  `form_component` varchar(64) DEFAULT NULL,
  `validation_json` json DEFAULT NULL,
  `default_value` varchar(255) DEFAULT NULL,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_column` (`tenant_id`, `table_id`, `column_name`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成字段定义';

CREATE TABLE IF NOT EXISTS `gen_index` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `table_id` bigint unsigned NOT NULL,
  `index_name` varchar(128) NOT NULL,
  `index_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `column_names` varchar(500) NOT NULL,
  `unique_flag` tinyint(1) NOT NULL DEFAULT 0,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_index` (`tenant_id`, `table_id`, `index_name`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成索引定义';

CREATE TABLE IF NOT EXISTS `gen_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `template_code` varchar(64) NOT NULL,
  `template_name` varchar(128) NOT NULL,
  `template_group` varchar(64) NOT NULL,
  `template_type` varchar(32) NOT NULL,
  `engine_type` varchar(32) NOT NULL DEFAULT 'FREEMARKER',
  `file_path_rule` varchar(255) NOT NULL,
  `content_text` mediumtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gen_template` (`tenant_id`, `template_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成模板';

CREATE TABLE IF NOT EXISTS `gen_run_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL,
  `module_id` bigint unsigned NOT NULL DEFAULT 0,
  `table_id` bigint unsigned NOT NULL DEFAULT 0,
  `run_type` varchar(32) NOT NULL DEFAULT 'FULL',
  `output_target` varchar(255) DEFAULT NULL,
  `generated_files_json` json DEFAULT NULL,
  `generated_sql_text` longtext,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `error_message` varchar(2000) DEFAULT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_gen_run_record` (`tenant_id`, `project_id`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='代码生成执行记录';

CREATE TABLE IF NOT EXISTS `audit_login_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_id` bigint unsigned NOT NULL DEFAULT 0,
  `username` varchar(64) DEFAULT NULL,
  `identity_type` varchar(32) DEFAULT NULL,
  `login_type` varchar(32) NOT NULL DEFAULT 'PASSWORD',
  `login_ip` varchar(64) DEFAULT NULL,
  `login_region` varchar(255) DEFAULT NULL,
  `device_info` varchar(500) DEFAULT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `fail_reason` varchar(500) DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_login_log_query` (`tenant_id`, `user_id`, `occurred_at`),
  KEY `idx_login_log_ip` (`tenant_id`, `login_ip`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录日志';

CREATE TABLE IF NOT EXISTS `audit_operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `trace_id` varchar(64) DEFAULT NULL,
  `operator_user_id` bigint unsigned NOT NULL DEFAULT 0,
  `operator_name` varchar(128) DEFAULT NULL,
  `biz_module` varchar(64) NOT NULL,
  `biz_type` varchar(64) DEFAULT NULL,
  `biz_id` varchar(64) DEFAULT NULL,
  `operation_type` varchar(32) NOT NULL,
  `request_uri` varchar(500) DEFAULT NULL,
  `http_method` varchar(16) DEFAULT NULL,
  `request_body` json DEFAULT NULL,
  `response_body` json DEFAULT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 1,
  `duration_ms` int NOT NULL DEFAULT 0,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_operation_log_query` (`tenant_id`, `biz_module`, `occurred_at`),
  KEY `idx_operation_log_operator` (`tenant_id`, `operator_user_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志';

CREATE TABLE IF NOT EXISTS `audit_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `event_code` varchar(64) NOT NULL,
  `event_name` varchar(128) NOT NULL,
  `event_level` varchar(32) NOT NULL DEFAULT 'INFO',
  `event_source` varchar(64) NOT NULL,
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` varchar(64) DEFAULT NULL,
  `operator_user_id` bigint unsigned NOT NULL DEFAULT 0,
  `detail_json` json DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_audit_event_query` (`tenant_id`, `event_code`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审计事件';

CREATE TABLE IF NOT EXISTS `sec_risk_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `rule_code` varchar(64) NOT NULL,
  `rule_name` varchar(128) NOT NULL,
  `risk_type` varchar(32) NOT NULL,
  `rule_expr` text NOT NULL,
  `action_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_risk_rule` (`tenant_id`, `rule_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='安全风控规则';

CREATE TABLE IF NOT EXISTS `sec_blacklist` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL DEFAULT 0,
  `black_type` varchar(32) NOT NULL,
  `black_value` varchar(255) NOT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `expired_at` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_blacklist` (`tenant_id`, `black_type`, `black_value`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='黑名单';

SET FOREIGN_KEY_CHECKS = 1;
