INSERT INTO `iam_menu` (
  `id`, `tenant_id`, `parent_id`, `menu_type`, `menu_code`, `menu_name`, `route_path`,
  `component_path`, `permission_code`, `icon`, `visible`, `keep_alive`, `sort_no`,
  `status`, `meta_json`, `remark`, `created_by`, `updated_by`
)
VALUES
  (100, 1, 3, 'MENU', 'iam_overview', '总览与基线', '/iam?tab=foundation', '@/views/iam/IamView.vue', 'iam:overview:query', 'Monitor', 1, 0, 20, 'ENABLED', JSON_OBJECT('tab', 'foundation'), 'IAM 总览控制面', 0, 0),
  (101, 1, 3, 'MENU', 'iam_organization', '组织与岗位', '/iam?tab=organization', '@/views/iam/IamView.vue', 'iam:user:query', 'OfficeBuilding', 1, 0, 21, 'ENABLED', JSON_OBJECT('tab', 'organization'), '组织主数据控制面', 0, 0),
  (102, 1, 3, 'MENU', 'iam_accounts', '用户与员工', '/iam?tab=accounts', '@/views/iam/IamView.vue', 'iam:user:query', 'UserFilled', 1, 0, 22, 'ENABLED', JSON_OBJECT('tab', 'accounts'), '用户与员工控制面', 0, 0),
  (103, 1, 3, 'MENU', 'iam_permissions', '角色与权限', '/iam?tab=permissions', '@/views/iam/IamView.vue', 'iam:role:query', 'Lock', 1, 0, 23, 'ENABLED', JSON_OBJECT('tab', 'permissions'), '角色与权限资源控制面', 0, 0),
  (104, 1, 3, 'MENU', 'iam_assignment', '授权编排', '/iam?tab=assignment', '@/views/iam/IamView.vue', 'iam:user-role:query', 'Connection', 1, 0, 28, 'ENABLED', JSON_OBJECT('tab', 'assignment'), '授权编排控制面', 0, 0),
  (110, 1, 2, 'MENU', 'tenant_overview', '租户总览', '/tenant?view=overview', '@/views/tenant/TenantView.vue', 'tenant:query', 'DataAnalysis', 1, 0, 10, 'ENABLED', JSON_OBJECT('view', 'overview'), '租户总览控制面', 0, 0),
  (111, 1, 2, 'MENU', 'tenant_onboarding', '开通治理', '/tenant?view=onboarding', '@/views/tenant/TenantView.vue', 'tenant:query', 'Promotion', 1, 0, 11, 'ENABLED', JSON_OBJECT('view', 'onboarding'), '租户开通治理控制面', 0, 0),
  (112, 1, 2, 'MENU', 'tenant_package', '套餐配额', '/tenant?view=package', '@/views/tenant/TenantView.vue', 'tenant:query', 'CollectionTag', 1, 0, 12, 'ENABLED', JSON_OBJECT('view', 'package'), '租户套餐与配额控制面', 0, 0),
  (113, 1, 2, 'MENU', 'tenant_isolation', '隔离升级', '/tenant?view=isolation', '@/views/tenant/TenantView.vue', 'tenant:query', 'SetUp', 1, 0, 13, 'ENABLED', JSON_OBJECT('view', 'isolation'), '租户隔离升级控制面', 0, 0),
  (114, 1, 2, 'MENU', 'tenant_ledger', '租户台账', '/tenant?view=ledger', '@/views/tenant/TenantView.vue', 'tenant:query', 'Document', 1, 0, 14, 'ENABLED', JSON_OBJECT('view', 'ledger'), '租户台账控制面', 0, 0),
  (120, 1, 8, 'MENU', 'system_overview', '系统总览', '/system?view=overview', '@/views/system/SystemView.vue', 'system:config:query', 'Monitor', 1, 0, 30, 'ENABLED', JSON_OBJECT('view', 'overview'), '系统总览控制面', 0, 0),
  (121, 1, 8, 'MENU', 'system_security', '安全策略', '/system?view=security', '@/views/system/SystemView.vue', 'system:config:query', 'Lock', 1, 0, 31, 'ENABLED', JSON_OBJECT('view', 'security'), '系统安全策略控制面', 0, 0),
  (122, 1, 8, 'MENU', 'system_locale', '语言字典', '/system?view=locale', '@/views/system/SystemView.vue', 'system:config:query', 'ChatLineRound', 1, 0, 32, 'ENABLED', JSON_OBJECT('view', 'locale'), '系统语言与字典控制面', 0, 0),
  (123, 1, 8, 'MENU', 'system_sequence', '序列规则', '/system?view=sequence', '@/views/system/SystemView.vue', 'system:config:query', 'Tickets', 1, 0, 33, 'ENABLED', JSON_OBJECT('view', 'sequence'), '系统序列规则控制面', 0, 0),
  (124, 1, 8, 'MENU', 'system_registry', '配置注册表', '/system?view=registry', '@/views/system/SystemView.vue', 'system:config:query', 'DocumentCopy', 1, 0, 34, 'ENABLED', JSON_OBJECT('view', 'registry'), '系统配置注册表控制面', 0, 0),
  (130, 1, 9, 'MENU', 'integration_overview', '集成总览', '/integration?view=overview', '@/views/integration/IntegrationView.vue', 'integration:datasource:query', 'Monitor', 1, 0, 40, 'ENABLED', JSON_OBJECT('view', 'overview'), '集成总览控制面', 0, 0),
  (131, 1, 9, 'MENU', 'integration_connection', '连接治理', '/integration?view=connection', '@/views/integration/IntegrationView.vue', 'integration:datasource:query', 'Connection', 1, 0, 41, 'ENABLED', JSON_OBJECT('view', 'connection'), '连接治理控制面', 0, 0),
  (132, 1, 9, 'MENU', 'integration_callback', '回调策略', '/integration?view=callback', '@/views/integration/IntegrationView.vue', 'integration:datasource:query', 'RefreshRight', 1, 0, 42, 'ENABLED', JSON_OBJECT('view', 'callback'), '回调策略控制面', 0, 0),
  (133, 1, 9, 'MENU', 'integration_health', '健康检测', '/integration?view=health', '@/views/integration/IntegrationView.vue', 'integration:datasource:query', 'CircleCheck', 1, 0, 43, 'ENABLED', JSON_OBJECT('view', 'health'), '集成健康检测控制面', 0, 0),
  (134, 1, 9, 'MENU', 'integration_registry', '接入台账', '/integration?view=registry', '@/views/integration/IntegrationView.vue', 'integration:datasource:query', 'DataBoard', 1, 0, 44, 'ENABLED', JSON_OBJECT('view', 'registry'), '接入台账控制面', 0, 0),
  (140, 1, 10, 'MENU', 'file_overview', '文件总览', '/file?view=overview', '@/views/file/FileCenterView.vue', 'file:object:query', 'Monitor', 1, 0, 50, 'ENABLED', JSON_OBJECT('view', 'overview'), '文件总览控制面', 0, 0),
  (141, 1, 10, 'MENU', 'file_storage', '存储策略', '/file?view=storage', '@/views/file/FileCenterView.vue', 'file:object:query', 'FolderOpened', 1, 0, 51, 'ENABLED', JSON_OBJECT('view', 'storage'), '文件存储策略控制面', 0, 0),
  (142, 1, 10, 'MENU', 'file_upload', '上传治理', '/file?view=upload', '@/views/file/FileCenterView.vue', 'file:object:query', 'UploadFilled', 1, 0, 52, 'ENABLED', JSON_OBJECT('view', 'upload'), '文件上传治理控制面', 0, 0),
  (143, 1, 10, 'MENU', 'file_lifecycle', '生命周期', '/file?view=lifecycle', '@/views/file/FileCenterView.vue', 'file:object:query', 'Timer', 1, 0, 53, 'ENABLED', JSON_OBJECT('view', 'lifecycle'), '文件生命周期控制面', 0, 0),
  (144, 1, 10, 'MENU', 'file_audit', '访问审计', '/file?view=audit', '@/views/file/FileCenterView.vue', 'file:object:query', 'Tickets', 1, 0, 54, 'ENABLED', JSON_OBJECT('view', 'audit'), '文件访问审计控制面', 0, 0),
  (150, 1, 11, 'MENU', 'scheduler_overview', '调度总览', '/scheduler?view=overview', '@/views/scheduler/SchedulerView.vue', 'scheduler:job:query', 'Monitor', 1, 0, 60, 'ENABLED', JSON_OBJECT('view', 'overview'), '调度总览控制面', 0, 0),
  (151, 1, 11, 'MENU', 'scheduler_strategy', '执行策略', '/scheduler?view=strategy', '@/views/scheduler/SchedulerView.vue', 'scheduler:job:query', 'Operation', 1, 0, 61, 'ENABLED', JSON_OBJECT('view', 'strategy'), '调度执行策略控制面', 0, 0),
  (152, 1, 11, 'MENU', 'scheduler_pipeline', '执行链路', '/scheduler?view=pipeline', '@/views/scheduler/SchedulerView.vue', 'scheduler:job:query', 'Share', 1, 0, 62, 'ENABLED', JSON_OBJECT('view', 'pipeline'), '调度执行链路控制面', 0, 0),
  (153, 1, 11, 'MENU', 'scheduler_alarm', '告警基线', '/scheduler?view=alarm', '@/views/scheduler/SchedulerView.vue', 'scheduler:job:query', 'Bell', 1, 0, 63, 'ENABLED', JSON_OBJECT('view', 'alarm'), '调度告警基线控制面', 0, 0),
  (154, 1, 11, 'MENU', 'scheduler_log', '日志治理', '/scheduler?view=log', '@/views/scheduler/SchedulerView.vue', 'scheduler:job:query', 'DocumentCopy', 1, 0, 64, 'ENABLED', JSON_OBJECT('view', 'log'), '调度日志治理控制面', 0, 0),
  (160, 1, 12, 'MENU', 'codegen_overview', '生成总览', '/codegen?view=overview', '@/views/codegen/CodegenView.vue', 'codegen:project:query', 'Monitor', 1, 0, 70, 'ENABLED', JSON_OBJECT('view', 'overview'), '代码生成总览控制面', 0, 0),
  (161, 1, 12, 'MENU', 'codegen_metadata', '元数据建模', '/codegen?view=metadata', '@/views/codegen/CodegenView.vue', 'codegen:project:query', 'Collection', 1, 0, 71, 'ENABLED', JSON_OBJECT('view', 'metadata'), '代码生成元数据建模控制面', 0, 0),
  (162, 1, 12, 'MENU', 'codegen_template', '模板基线', '/codegen?view=template', '@/views/codegen/CodegenView.vue', 'codegen:project:query', 'MagicStick', 1, 0, 72, 'ENABLED', JSON_OBJECT('view', 'template'), '代码生成模板基线控制面', 0, 0),
  (163, 1, 12, 'MENU', 'codegen_gate', '交付门禁', '/codegen?view=gate', '@/views/codegen/CodegenView.vue', 'codegen:project:query', 'Finished', 1, 0, 73, 'ENABLED', JSON_OBJECT('view', 'gate'), '代码生成交付门禁控制面', 0, 0),
  (164, 1, 12, 'MENU', 'codegen_artifact', '产物矩阵', '/codegen?view=artifact', '@/views/codegen/CodegenView.vue', 'codegen:project:query', 'Files', 1, 0, 74, 'ENABLED', JSON_OBJECT('view', 'artifact'), '代码生成产物矩阵控制面', 0, 0),
  (170, 1, 13, 'MENU', 'audit_overview', '审计总览', '/audit?view=overview', '@/views/audit/AuditView.vue', 'audit:operation:query', 'Monitor', 1, 0, 80, 'ENABLED', JSON_OBJECT('view', 'overview'), '审计总览控制面', 0, 0),
  (171, 1, 13, 'MENU', 'audit_trail', '审计留痕', '/audit?view=trail', '@/views/audit/AuditView.vue', 'audit:operation:query', 'DocumentChecked', 1, 0, 81, 'ENABLED', JSON_OBJECT('view', 'trail'), '审计留痕控制面', 0, 0),
  (172, 1, 13, 'MENU', 'audit_risk', '风险识别', '/audit?view=risk', '@/views/audit/AuditView.vue', 'audit:operation:query', 'Warning', 1, 0, 82, 'ENABLED', JSON_OBJECT('view', 'risk'), '风险识别控制面', 0, 0),
  (173, 1, 13, 'MENU', 'audit_blacklist', '黑名单', '/audit?view=blacklist', '@/views/audit/AuditView.vue', 'audit:operation:query', 'CircleCloseFilled', 1, 0, 83, 'ENABLED', JSON_OBJECT('view', 'blacklist'), '黑名单控制面', 0, 0),
  (174, 1, 13, 'MENU', 'audit_catalog', '高危目录', '/audit?view=catalog', '@/views/audit/AuditView.vue', 'audit:operation:query', 'DataAnalysis', 1, 0, 84, 'ENABLED', JSON_OBJECT('view', 'catalog'), '高危目录控制面', 0, 0)
AS new
ON DUPLICATE KEY UPDATE
  `parent_id` = new.`parent_id`,
  `menu_type` = new.`menu_type`,
  `menu_name` = new.`menu_name`,
  `route_path` = new.`route_path`,
  `component_path` = new.`component_path`,
  `permission_code` = new.`permission_code`,
  `icon` = new.`icon`,
  `visible` = new.`visible`,
  `keep_alive` = new.`keep_alive`,
  `sort_no` = new.`sort_no`,
  `status` = new.`status`,
  `meta_json` = new.`meta_json`,
  `remark` = new.`remark`,
  `updated_by` = new.`updated_by`;
